// To regenerate the go code, run make protobuf

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: repo-agent/otel-portal/api/private/storage/file.proto

package storage

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WellKnownTypeCode int32

const (
	WellKnownTypeCode_WellKnownTypeCode_Unknown    WellKnownTypeCode = 0
	WellKnownTypeCode_WellKnownTypeCode_ObjectType WellKnownTypeCode = 1
)

// Enum value maps for WellKnownTypeCode.
var (
	WellKnownTypeCode_name = map[int32]string{
		0: "WellKnownTypeCode_Unknown",
		1: "WellKnownTypeCode_ObjectType",
	}
	WellKnownTypeCode_value = map[string]int32{
		"WellKnownTypeCode_Unknown":    0,
		"WellKnownTypeCode_ObjectType": 1,
	}
)

func (x WellKnownTypeCode) Enum() *WellKnownTypeCode {
	p := new(WellKnownTypeCode)
	*p = x
	return p
}

func (x WellKnownTypeCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WellKnownTypeCode) Descriptor() protoreflect.EnumDescriptor {
	return file_repo_agent_otel_portal_api_private_storage_file_proto_enumTypes[0].Descriptor()
}

func (WellKnownTypeCode) Type() protoreflect.EnumType {
	return &file_repo_agent_otel_portal_api_private_storage_file_proto_enumTypes[0]
}

func (x WellKnownTypeCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WellKnownTypeCode.Descriptor instead.
func (WellKnownTypeCode) EnumDescriptor() ([]byte, []int) {
	return file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescGZIP(), []int{0}
}

// ObjectType is used to identify the type of objects in the file.
// Each object has a header, and there is a type_code value in the header.
// Before an object is written, the type information must have been recorded with an ObjectType record.
type ObjectType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeCode uint32 `protobuf:"varint,1,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	TypeName string `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *ObjectType) Reset() {
	*x = ObjectType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repo_agent_otel_portal_api_private_storage_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectType) ProtoMessage() {}

func (x *ObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_repo_agent_otel_portal_api_private_storage_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectType.ProtoReflect.Descriptor instead.
func (*ObjectType) Descriptor() ([]byte, []int) {
	return file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectType) GetTypeCode() uint32 {
	if x != nil {
		return x.TypeCode
	}
	return 0
}

func (x *ObjectType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

var File_repo_agent_otel_portal_api_private_storage_file_proto protoreflect.FileDescriptor

var file_repo_agent_otel_portal_api_private_storage_file_proto_rawDesc = []byte{
	0x0a, 0x35, 0x72, 0x65, 0x70, 0x6f, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6f, 0x74, 0x65,
	0x6c, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x22, 0x46, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x54, 0x0a, 0x11, 0x57, 0x65, 0x6c, 0x6c,
	0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a,
	0x19, 0x57, 0x65, 0x6c, 0x6c, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c,
	0x57, 0x65, 0x6c, 0x6c, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x42, 0x62,
	0x5a, 0x60, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6b, 0x65,
	0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x67, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2d, 0x66, 0x6f, 0x72,
	0x2d, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2d, 0x64, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x2d, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2f, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescOnce sync.Once
	file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescData = file_repo_agent_otel_portal_api_private_storage_file_proto_rawDesc
)

func file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescGZIP() []byte {
	file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescOnce.Do(func() {
		file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescData)
	})
	return file_repo_agent_otel_portal_api_private_storage_file_proto_rawDescData
}

var file_repo_agent_otel_portal_api_private_storage_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repo_agent_otel_portal_api_private_storage_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_repo_agent_otel_portal_api_private_storage_file_proto_goTypes = []interface{}{
	(WellKnownTypeCode)(0), // 0: storage.WellKnownTypeCode
	(*ObjectType)(nil),     // 1: storage.ObjectType
}
var file_repo_agent_otel_portal_api_private_storage_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repo_agent_otel_portal_api_private_storage_file_proto_init() }
func file_repo_agent_otel_portal_api_private_storage_file_proto_init() {
	if File_repo_agent_otel_portal_api_private_storage_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_repo_agent_otel_portal_api_private_storage_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repo_agent_otel_portal_api_private_storage_file_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repo_agent_otel_portal_api_private_storage_file_proto_goTypes,
		DependencyIndexes: file_repo_agent_otel_portal_api_private_storage_file_proto_depIdxs,
		EnumInfos:         file_repo_agent_otel_portal_api_private_storage_file_proto_enumTypes,
		MessageInfos:      file_repo_agent_otel_portal_api_private_storage_file_proto_msgTypes,
	}.Build()
	File_repo_agent_otel_portal_api_private_storage_file_proto = out.File
	file_repo_agent_otel_portal_api_private_storage_file_proto_rawDesc = nil
	file_repo_agent_otel_portal_api_private_storage_file_proto_goTypes = nil
	file_repo_agent_otel_portal_api_private_storage_file_proto_depIdxs = nil
}
